In [1]:
import datetime as dt

import pandas as pd

from winterload import COORDINATES
from winterload.source.openmeteo import OpenMeteo

test = COORDINATES[0]  # test with Basel
start_date = dt.date(2022, 1, 1)
end_date = dt.date(2022, 12, 31)
data = OpenMeteo().get_weather_historic(test["lat"], test["lon"], start_date=start_date, end_date=end_date)
df_hourly = pd.DataFrame(data[1]["hourly"])
df_hourly.head(5)

Getting historical weather data between 2022-01-01 and 2022-12-31 at (47.559601,7.588576)

Coordinates: 47.56281280517578°N 7.5899338722229°E
Elevation: 247.0 m asl
Timezone difference to GMT+0: 0s
Model Nº: 1

,date,temperature_2m,precipitation,rain,apparent_temperature,dew_point_2m,relative_humidity_2m,snowfall,snow_depth,cloud_cover,...,cloud_cover_high,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m,wet_bulb_temperature_2m,cloud_base,sunshine_duration,snowfall_height,freezing_level_height
0,2022-01-01 00:00:00+00:00,5.10,0.0,0.0,2.840458,2.30,82.117813,0.0,0.0,0.0,...,0.0,998.641296,3.545589,156.037506,7.559999,3.404640,NaN,0.0,NaN,3590.0
1,2022-01-01 01:00:00+00:00,6.85,0.0,0.0,4.720113,2.10,71.737793,0.0,0.0,0.0,...,0.0,998.829529,2.414953,206.564987,6.120000,4.179008,NaN,0.0,NaN,3620.0
2,2022-01-01 02:00:00+00:00,4.60,0.0,0.0,1.688284,1.00,77.478577,0.0,0.0,3.0,...,3.0,998.781128,6.489992,183.179764,9.000000,2.535414,NaN,0.0,NaN,3630.0
3,2022-01-01 03:00:00+00:00,3.00,0.0,0.0,-0.384130,0.55,83.936569,0.0,0.0,0.0,...,0.0,998.606140,9.227524,159.443878,11.520000,1.523525,NaN,0.0,NaN,3650.0
4,2022-01-01 04:00:00+00:00,2.60,0.0,0.0,-0.650993,0.75,87.605042,0.0,0.0,0.0,...,0.0,998.077209,8.534353,152.354111,12.240000,1.432786,NaN,0.0,NaN,3650.0

In [2]:
import datetime as dt

import pandas as pd

from winterload.source.frauenhofer_ise import FrauenhoferISE

start_date = dt.datetime(2022, 1, 1, 0, 0, 0)
end_date = dt.datetime(2022, 12, 31, 23, 59, 59)
data = FrauenhoferISE().get_public_power(start_date, end_date)
df_public_power = pd.DataFrame(data)
df_public_power.head(5)

,timestamp,cross_border_electricity_trading,nuclear,hydro_run_of_river,hydro_water_reservoir,hydro_pumped_storage,others,wind_onshore,solar,load,residual_load,renewable_share_of_load,renewable_share_of_generation
0,2022-01-01T00:00:00+01:00,1960.6,2960.5,1862.1,260.1,17.1,421.1,27.4,0.0,7892.9,7865.5,27.2,38.9
1,2022-01-01T01:00:00+01:00,1957.0,2963.9,1913.9,279.8,45.6,421.1,16.1,0.0,8023.4,8007.3,27.5,39.5
2,2022-01-01T02:00:00+01:00,2333.6,2961.4,2088.8,252.0,44.5,421.1,14.3,0.0,7824.3,7810.0,30.1,41.0
3,2022-01-01T03:00:00+01:00,2354.4,2963.9,1988.6,201.1,48.8,421.1,12.8,0.0,8009.1,7996.3,27.5,39.4
4,2022-01-01T04:00:00+01:00,2141.7,2964.5,1828.0,202.8,22.0,421.1,9.6,0.0,8089.8,8080.2,25.2,37.6

In [3]:
import datetime as dt

import pandas as pd

from winterload.source.entso_e import EntsoE

start_date = dt.datetime(2023, 1, 1, 0, 0, 0)
end_date = dt.datetime(2023, 12, 31, 23, 59, 59)
data = EntsoE().get_load(start_date, end_date)
df_load = pd.DataFrame(data)
df_load.head(5)

                  timestamp  quantity      bidding_zone unit
0 2023-01-01 00:00:00+00:00   7373.01  10YCH-SWISSGRIDZ  MAW
1 2023-01-01 01:00:00+00:00   7464.26  10YCH-SWISSGRIDZ  MAW
2 2023-01-01 02:00:00+00:00   6896.76  10YCH-SWISSGRIDZ  MAW
3 2023-01-01 03:00:00+00:00   7145.96  10YCH-SWISSGRIDZ  MAW
4 2023-01-01 04:00:00+00:00   7148.45  10YCH-SWISSGRIDZ  MAW

In [3]:
import datetime as dt

from winterload.pipeline.features.weather_forecast_backfill import build_range

start_date = dt.datetime(2025, 9, 23, 0, 0, 0)
end_date = dt.datetime(2025, 10, 23, 23, 59, 59)
written, skipped = build_range(start_date, end_date)

KeyboardInterrupt: